char let_A[9][9]={  "  xxxx  ",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx"};
char let_B[9][9]={  "xxxxxx",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxx  "};
char let_C[9][9]={  "xxxxxxxx",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xxxxxxxx"};
char let_D[9][9]={  "xxxxxx  ",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxx  "};

char let_E[9][9]={  "xxxxxxxx",
					"xx      ",
					"xx      ",
					"xxxxxxxx",
					"xx      ",
					"xx      ",
					"xx      ",
					"xxxxxxxx"};
char let_F[9][9]={  "xxxxxxxx",
					"xx      ",
					"xx      ",
					"xxxxxxxx",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      "};
char let_G[9][9]={  "xxxxxxxx",
					"xx      ",
					"xx      ",
					"xx xxxxx",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx"};
char let_H[9][9]={  "xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xx    xx"};
char let_I[9][9]={  "xxxxxxxx",
					"    x   ",
					"    x   ",
					"    x   ",
					"    x   ",
					"    x   ",
					"    x   ",
					"xxxxxxxx"};
char let_J[9][9]={  "xxxxxxxx",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"xxxxx   "};
char let_K[9][9]={  "xx    xx",
					"xx  xx  ",
					"xx xx   ",
					"xxxx    ",
					"xx xx   ",
					"xx  xx  ",
					"xx   xx ",
					"xx    xx"};
char let_L[9][9]={  "xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xxxxxxxx"};
char let_M[9][9]={  "x      x",
					"xx    xx",
					"x x  x x",
					"x  xx  x",
					"x      x",
					"x      x",
					"x      x"};
char let_N[9][9]={  "xx    xx",
					"xxx   xx",
				   	"xxxx  xx",
				   	"xx xx xx",
				   	"xx  x xx",
				   	"xx  xxxx",
				 	"xx   xxx",
				 	"xx    xx"};
char let_O[9][9]={  "xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx"};
char let_P[9][9]={  "xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xxxxxx ",
					"xx      ",
					"xx      ",
					"xx      ",
					"xx      "};
char let_Q[9][9]={  "xxxxxxxx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxxx ",
					"      xx"};
char let_R[9][9]={  "xxxxxxx ",
					"xx    xx",
					"xx    xx",
					"xxxxxxx ",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx"};
char let_S[9][9]={  " xxxxxx ",
					"xx    xx",
					"xx      ",
					"xx      ",
					"  xxxxx ",
					"      xx",
					"      xx",
					"xxxxxxx ",
					"        "};

char let_T[9][9]={  "xxxxxxxx",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   "};
char let_U[9][9]={  "xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxxxxxxx"};
char let_V[9][9]={  "xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xxx  xxx",
					"  xxxx  "};
char let_W[9][9]={  "xx    xx",
					"xx    xx",
					"xx    xx",
					"xx    xx",
					"xx xx xx",
					"xx xx xx",
					"xxx  xxx",
					"xx    xx"};
					
char let_X[9][9]={  "x      x",
					" x    x ",
					"  x  x  ",
					"   xx   ",
					"  x  x  ",
					" x    x ",
					"x      x",
					"        "};
char let_Y[9][9]={  "xx    xx",
					"xx    xx",
					" xx  xx ",
					"  x  x  ",
					"   xx   ",
					"   xx   ",
					"   xx   ",
					"   xx   "};
char let_Z[9][9]={  "xxxxxxxx",
					"      xx",
					"     xx ",
					"    xx  ",
					"   xx   ",
					" xx     ",
					"xx      ",
					"xxxxxxxx"};