// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sum.proto
#ifndef GRPC_sum_2eproto__INCLUDED
#define GRPC_sum_2eproto__INCLUDED

#include "sum.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sum {

class SumService final {
 public:
  static constexpr char const* service_full_name() {
    return "sum.SumService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Sum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::sum::SumResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>> AsyncSum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>>(AsyncSumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>> PrepareAsyncSum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>>(PrepareAsyncSumRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>* AsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sum::SumResponse>* PrepareAsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Sum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::sum::SumResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>> AsyncSum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>>(AsyncSumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>> PrepareAsyncSum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>>(PrepareAsyncSumRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, std::function<void(::grpc::Status)>) override;
      void Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>* AsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sum::SumResponse>* PrepareAsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Sum_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Sum(::grpc::ServerContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Sum() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSum(::grpc::ServerContext* context, ::sum::SumRequest* request, ::grpc::ServerAsyncResponseWriter< ::sum::SumResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Sum<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Sum() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sum::SumRequest, ::sum::SumResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response) { return this->Sum(context, request, response); }));}
    void SetMessageAllocatorFor_Sum(
        ::grpc::MessageAllocator< ::sum::SumRequest, ::sum::SumResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sum::SumRequest, ::sum::SumResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sum(
      ::grpc::CallbackServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Sum<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Sum() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Sum() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSum(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Sum() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Sum(context, request, response); }));
    }
    ~WithRawCallbackMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sum(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Sum() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sum::SumRequest, ::sum::SumResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sum::SumRequest, ::sum::SumResponse>* streamer) {
                       return this->StreamedSum(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Sum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sum(::grpc::ServerContext* /*context*/, const ::sum::SumRequest* /*request*/, ::sum::SumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSum(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sum::SumRequest,::sum::SumResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Sum<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Sum<Service > StreamedService;
};

}  // namespace sum


#endif  // GRPC_sum_2eproto__INCLUDED
