// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sum.proto

#include "sum.pb.h"
#include "sum.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sum {

static const char* SumService_method_names[] = {
  "/sum.SumService/Sum",
};

std::unique_ptr< SumService::Stub> SumService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SumService::Stub> stub(new SumService::Stub(channel, options));
  return stub;
}

SumService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Sum_(SumService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SumService::Stub::Sum(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::sum::SumResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sum::SumRequest, ::sum::SumResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sum_, context, request, response);
}

void SumService::Stub::async::Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sum::SumRequest, ::sum::SumResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sum_, context, request, response, std::move(f));
}

void SumService::Stub::async::Sum(::grpc::ClientContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sum::SumResponse>* SumService::Stub::PrepareAsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sum::SumResponse, ::sum::SumRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sum::SumResponse>* SumService::Stub::AsyncSumRaw(::grpc::ClientContext* context, const ::sum::SumRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSumRaw(context, request, cq);
  result->StartCall();
  return result;
}

SumService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SumService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SumService::Service, ::sum::SumRequest, ::sum::SumResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SumService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sum::SumRequest* req,
             ::sum::SumResponse* resp) {
               return service->Sum(ctx, req, resp);
             }, this)));
}

SumService::Service::~Service() {
}

::grpc::Status SumService::Service::Sum(::grpc::ServerContext* context, const ::sum::SumRequest* request, ::sum::SumResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sum

